export enum UserType {
  INSPECTOR = 'INSPECTOR',
  CARETAKER = 'CARETAKER',
  WINDOW_USER = 'WINDOW_USER',
  CHECKIN_MONITOR_INSPECTOR = 'CHECKIN_MONITOR_INSPECTOR',

  DISPENSARY = 'DISPENSARY',
  FRONT_OFFICE = 'FRONT_OFFICE',
  FINANCIAL = 'FINANCIAL',
  ADMIN = 'ADMIN',

  PET_OWNER = 'PET_OWNER',

  CONTRACTOR = 'CONTRACTOR',
}

export enum PetAppDocumentType {
  HIPOP = 'HIPOP',
  ORIGINAL = 'Original',
  COPY = 'Copy',
}
